// Code generated by MockGen. DO NOT EDIT.
// Source: ./database/postgres.go

// Package mocks is a generated GoMock package.
package mocks

import (
	sql "database/sql"
	reflect "reflect"
	database "loanservice/database"

	gomock "github.com/golang/mock/gomock"
)

// MockPostgresClient is a mock of PostgresClient interface.
type MockPostgresClient struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresClientMockRecorder
}

// MockPostgresClientMockRecorder is the mock recorder for MockPostgresClient.
type MockPostgresClientMockRecorder struct {
	mock *MockPostgresClient
}

// NewMockPostgresClient creates a new mock instance.
func NewMockPostgresClient(ctrl *gomock.Controller) *MockPostgresClient {
	mock := &MockPostgresClient{ctrl: ctrl}
	mock.recorder = &MockPostgresClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresClient) EXPECT() *MockPostgresClientMockRecorder {
	return m.recorder
}

// CommitTransaction mocks base method.
func (m *MockPostgresClient) CommitTransaction(arg0 *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTransaction", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTransaction indicates an expected call of CommitTransaction.
func (mr *MockPostgresClientMockRecorder) CommitTransaction(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTransaction", reflect.TypeOf((*MockPostgresClient)(nil).CommitTransaction), arg0)
}

// CreateOrInsertAccount mocks base method.
func (m *MockPostgresClient) CreateOrInsertAccount(req database.CreateAccountReqDb) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrInsertAccount", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrInsertAccount indicates an expected call of CreateOrInsertAccount.
func (mr *MockPostgresClientMockRecorder) CreateOrInsertAccount(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrInsertAccount", reflect.TypeOf((*MockPostgresClient)(nil).CreateOrInsertAccount), req)
}

// CreateOrInsertEmployee mocks base method.
func (m *MockPostgresClient) CreateOrInsertEmployee(req database.CreateEmployeeReqDb) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrInsertEmployee", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrInsertEmployee indicates an expected call of CreateOrInsertEmployee.
func (mr *MockPostgresClientMockRecorder) CreateOrInsertEmployee(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrInsertEmployee", reflect.TypeOf((*MockPostgresClient)(nil).CreateOrInsertEmployee), req)
}

// GetAccount mocks base method.
func (m *MockPostgresClient) GetAccount(req database.GetAccountReqDb) (database.GetAccountResDb, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", req)
	ret0, _ := ret[0].(database.GetAccountResDb)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockPostgresClientMockRecorder) GetAccount(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockPostgresClient)(nil).GetAccount), req)
}

// GetAccountWithCredentials mocks base method.
func (m *MockPostgresClient) GetAccountWithCredentials(req database.GetAccountWithCredentialsReqDb) (database.GetAccountWithCredentialsResDb, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountWithCredentials", req)
	ret0, _ := ret[0].(database.GetAccountWithCredentialsResDb)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountWithCredentials indicates an expected call of GetAccountWithCredentials.
func (mr *MockPostgresClientMockRecorder) GetAccountWithCredentials(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountWithCredentials", reflect.TypeOf((*MockPostgresClient)(nil).GetAccountWithCredentials), req)
}

// GetEmployee mocks base method.
func (m *MockPostgresClient) GetEmployee(req database.GetEmployeeReqDb) (database.GetEmployeeResDb, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployee", req)
	ret0, _ := ret[0].(database.GetEmployeeResDb)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployee indicates an expected call of GetEmployee.
func (mr *MockPostgresClientMockRecorder) GetEmployee(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployee", reflect.TypeOf((*MockPostgresClient)(nil).GetEmployee), req)
}

// GetEmployeeWithCredentials mocks base method.
func (m *MockPostgresClient) GetEmployeeWithCredentials(req database.GetEmployeeWithCredentialsReqDb) (database.GetEmployeeWithCredentialsResDb, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeWithCredentials", req)
	ret0, _ := ret[0].(database.GetEmployeeWithCredentialsResDb)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeWithCredentials indicates an expected call of GetEmployeeWithCredentials.
func (mr *MockPostgresClientMockRecorder) GetEmployeeWithCredentials(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeWithCredentials", reflect.TypeOf((*MockPostgresClient)(nil).GetEmployeeWithCredentials), req)
}

// GetLoan mocks base method.
func (m *MockPostgresClient) GetLoan(req database.GetLoanReqDb) (database.GetLoanResDb, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoan", req)
	ret0, _ := ret[0].(database.GetLoanResDb)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoan indicates an expected call of GetLoan.
func (mr *MockPostgresClientMockRecorder) GetLoan(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoan", reflect.TypeOf((*MockPostgresClient)(nil).GetLoan), req)
}

// GetLoanInvestments mocks base method.
func (m *MockPostgresClient) GetLoanInvestments(req database.GetLoanInvestmentsReqDb) (database.GetLoanInvestmentsResDb, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoanInvestments", req)
	ret0, _ := ret[0].(database.GetLoanInvestmentsResDb)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoanInvestments indicates an expected call of GetLoanInvestments.
func (mr *MockPostgresClientMockRecorder) GetLoanInvestments(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoanInvestments", reflect.TypeOf((*MockPostgresClient)(nil).GetLoanInvestments), req)
}

// InsertLoan mocks base method.
func (m *MockPostgresClient) InsertLoan(req database.InsertLoanReqDb) (database.InsertLoanResDb, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLoan", req)
	ret0, _ := ret[0].(database.InsertLoanResDb)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertLoan indicates an expected call of InsertLoan.
func (mr *MockPostgresClientMockRecorder) InsertLoan(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLoan", reflect.TypeOf((*MockPostgresClient)(nil).InsertLoan), req)
}

// InsertLoanApproval mocks base method.
func (m *MockPostgresClient) InsertLoanApproval(req database.InsertLoanApprovalReqDb, tx *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLoanApproval", req, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertLoanApproval indicates an expected call of InsertLoanApproval.
func (mr *MockPostgresClientMockRecorder) InsertLoanApproval(req, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLoanApproval", reflect.TypeOf((*MockPostgresClient)(nil).InsertLoanApproval), req, tx)
}

// InsertLoanDisbursement mocks base method.
func (m *MockPostgresClient) InsertLoanDisbursement(req database.InsertLoanDisbursementReqDb, tx *sql.Tx) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLoanDisbursement", req, tx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertLoanDisbursement indicates an expected call of InsertLoanDisbursement.
func (mr *MockPostgresClientMockRecorder) InsertLoanDisbursement(req, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLoanDisbursement", reflect.TypeOf((*MockPostgresClient)(nil).InsertLoanDisbursement), req, tx)
}

// InsertLoanInvestment mocks base method.
func (m *MockPostgresClient) InsertLoanInvestment(req database.InsertLoanInvestmentReqDb, tx *sql.Tx) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLoanInvestment", req, tx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertLoanInvestment indicates an expected call of InsertLoanInvestment.
func (mr *MockPostgresClientMockRecorder) InsertLoanInvestment(req, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLoanInvestment", reflect.TypeOf((*MockPostgresClient)(nil).InsertLoanInvestment), req, tx)
}

// StartTransaction mocks base method.
func (m *MockPostgresClient) StartTransaction() (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTransaction")
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTransaction indicates an expected call of StartTransaction.
func (mr *MockPostgresClientMockRecorder) StartTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTransaction", reflect.TypeOf((*MockPostgresClient)(nil).StartTransaction))
}

// UpdateLoanStatus mocks base method.
func (m *MockPostgresClient) UpdateLoanStatus(req database.UpdateLoanStatusReqDb, tx *sql.Tx) (database.UpdateLoanStatusResDb, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoanStatus", req, tx)
	ret0, _ := ret[0].(database.UpdateLoanStatusResDb)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLoanStatus indicates an expected call of UpdateLoanStatus.
func (mr *MockPostgresClientMockRecorder) UpdateLoanStatus(req, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoanStatus", reflect.TypeOf((*MockPostgresClient)(nil).UpdateLoanStatus), req, tx)
}
